name: Angebot/Projekt einreichen
description: Listing einreichen (Immobilie, Dienstleistung, Idee, Projekt)
labels: ["submission", "needs-review"]
body:
  - type: input
    id: title
    attributes:
      label: Titel
      placeholder: z.B. 2-Zi.-Wohnung / Küchenstudio / Sanierungsprojekt
    validations: { required: true }
  - type: dropdown
    id: category
    attributes:
      label: Kategorie
      options:
        - Wohnung
        - Haus
        - Gewerbe
        - Projekt/Idee
        - Dienstleistung/Handwerk
        - Design/Homestaging
        - Garten/Landschaft
        - Möbel/Interior
        - Energie/Heizung
    validations: { required: true }
  - type: input
    id: location
    attributes:
      label: Ort
      placeholder: z.B. Berlin-Prenzlauer Berg
  - type: input
    id: price
    attributes:
      label: Preis/Preisrange
      placeholder: z.B. 1.500 € kalt / 520.000 €
  - type: textarea
    id: description
    attributes:
      label: Beschreibung
      placeholder: Kurzbeschreibung, Besonderheiten, Fläche, Baujahr etc.
  - type: textarea
    id: images
    attributes:
      label: Bild-URLs (eine pro Zeile)
      placeholder: https://...jpg
  - type: input
    id: contact
    attributes:
      label: Kontakt (sichtbar)
      placeholder: E-Mail, Website, Tel, Insta
  - type: checkboxes
    id: terms
    attributes:
      label: Bestätigung
      options:
        - label: Ich habe die Rechte an den Inhalten/Bildern und bin verantwortlich.
          required: true
name: Angebot/Projekt einreichen
description: Listing einreichen (Immobilie, Dienstleistung, Idee, Projekt)
labels: ["submission", "needs-review"]
body:
  - type: input
    id: title
    attributes:
      label: Titel
      placeholder: z.B. 2-Zi.-Wohnung Prenzlauer Berg / Küchenstudio / Sanierungsprojekt
    validations: { required: true }
  - type: dropdown
    id: category
    attributes:
      label: Kategorie
      options:
        - Wohnung
        - Haus
        - Gewerbe
        - Projekt/Idee
        - Dienstleistung/Handwerk
        - Design/Homestaging
        - Garten/Landschaft
        - Möbel/Interior
        - Energie/Heizung
    validations: { required: true }
  - type: input
    id: location
    attributes:
      label: Ort
      placeholder: z.B. Berlin-Prenzlauer Berg
  - type: input
    id: price
    attributes:
      label: Preis/Preisrange
      placeholder: z.B. 1.500 € kalt / 520.000 €
  - type: textarea
    id: description
    attributes:
      label: Beschreibung
      placeholder: Kurzbeschreibung, Besonderheiten, Zustand, Fläche, Baujahr etc.
  - type: textarea
    id: images
    attributes:
      label: Bild-URLs (eine pro Zeile)
      placeholder: https://...jpg
  - type: input
    id: contact
    attributes:
      label: Kontakt (sichtbar)
      placeholder: E-Mail, Website, Tel, Insta
  - type: checkboxes
    id: terms
    attributes:
      label: Bestätigung
      options:
        - label: Ich habe die Rechte an den Inhalten/Bildern und bin verantwortlich.
          required: true
