name: Projekt einreichen
description: Reiche ein Projekt/Immobilie/Service/Inspiration ein (wird manuell geprüft).
title: "[Einreichung] Kurztitel hier"
labels: ["submission","needs-review"]
body:
  - type: input
    id: typ
    attributes: { label: Typ, placeholder: "Immobilie / Handwerk / Design / Energie / Service" }
    validations: { required: true }
  - type: input
    id: ort
    attributes: { label: Ort, placeholder: "Berlin, Potsdam, ..." }
  - type: input
    id: kontakt
    attributes: { label: Kontakt/Website, placeholder: "E-Mail oder URL" }
  - type: textarea
    id: beschreibung
    attributes: { label: Kurzbeschreibung, description: "3–6 Sätze, verständlich." }
    validations: { required: true }
  - type: textarea
    id: details
    attributes: { label: Details/Links/Bilder, description: "Links zu Fotos/Plänen/Referenzen (URLs)." }
