name: Gebot (Bieterverfahren)
description: Gebot für ein Objekt abgeben
title: "[Gebot] Objekt: <Kurzname> – <Dein Betrag in EUR>"
labels: ["gebot","review-pending"]
body:
  - type: input
    id: objekt
    attributes:
      label: Objekt / Referenz
      placeholder: "z.B. Wohnung Boxhagener 12 / REF-2025-001"
    validations: {required: true}
  - type: input
    id: betrag
    attributes:
      label: Gebot (EUR)
      placeholder: "z.B. 512000"
    validations: {required: true}
  - type: textarea
    id: details
    attributes:
      label: Hinweise (Finanzierung, Frist, Bedingungen)
      placeholder: "z.B. Finanzierungsbestätigung folgt, Notar Termin möglich ab ..."
  - type: checkboxes
    id: consent
    attributes:
      label: Einverständnis
      options:
        - label: "Ich bestätige, dass die Angaben wahrheitsgemäß sind und öffentlich sichtbar werden."
          required: true
