name: Build Section Sitemaps
on:
  schedule:
    - cron: "6 3 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.x' }
      - run: python scripts/build_sitemaps.py
      - name: Commit sitemap
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add sitemap-sections.xml
          git commit -m "Update section sitemap" || echo "No changes"
          git push
