name: Update news and listings
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - run: pip install feedparser
    - run: python scripts/update_data.py
    - run: |
        git config --local user.name 'github-actions'
        git config --local user.email 'actions@users.noreply.github.com'
        git add data/news.json data/listings.json
        git commit -m 'Update news and listings from RSS feeds' || echo 'No changes'
        git push
